Repository SV-Summer-BootCamp-Team-F/backend, pull requests merged in 2023-07, with the labels that each got.

#3 docs: 리드미, 커밋 컨벤션 파일 적용, 추가
  .idea/vcs.xml
  README.md
  myapp/.gitmessage.txt
Labels: docs

#6 [Config] requirements.txt 수정합니다~
  .gitmessage.txt
  requirements.txt
Labels: chore

#7 Config/modify requirements
  requirements.txt
Labels: chore

#18 feature/user
  backend/settings.py
  backend/urls.py
  db.sqlite3
  myapp/migrations/__init__.py
  neo_db/__init__.py
  neo_db/admin.py
  neo_db/apps.py
  neo_db/migrations/0001_initial.py
  neo_db/migrations/__init__.py
  neo_db/models.py
  neo_db/serializers.py
  neo_db/urls.py
  neo_db/views.py
  sample_swagger/apps.py
  sample_swagger/models.py
  sample_swagger/serializers.py
  sample_swagger/urls.py
  sample_swagger/views.py
Labels: feature

#26 Config/test connect 25
  .idea/dataSources.xml
  .idea/django_ex.iml
  .idea/misc.xml
  Dockerfile
  backend/settings.py
  backend/urls.py
  db.sqlite3
  docker-compose.yml
  myapp/__init__.py
  myapp/apps.py
  myapp/models.py
  myapp/tests.py
  myapp/views.py
  neo_db/migrations/0002_delete_user.py
  neo_db/models.py
  neo_db/serializers.py
  neo_db/urls.py
  neo_db/views.py
  requirements.txt
  sample_swagger/admin.py
  sample_swagger/migrations/__init__.py
  sample_swagger/tests.py
Labels: chore, refactor, feature

#27 Config/test connect 25(최종본)
  neo_db/models.py
  neo_db/serializers.py
  neo_db/urls.py
  neo_db/views.py
Labels: feature

#30 Config/test connect 25
  backend/settings.py
  neo_db/serializers.py
  neo_db/static/person.png
  neo_db/urls.py
  neo_db/views.py
Labels: chore, docs, refactor, feature
